# Generated by Django 3.1.2 on 2020-10-31 09:02

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dolzhnost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('code', models.CharField(max_length=10, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Dolzhnost',
                'verbose_name_plural': 'Dolzhnosty',
            },
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='first name')),
                ('middle_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='middle name')),
                ('last_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='last name')),
                ('phone', models.CharField(blank=True, max_length=40, null=True, verbose_name='phone')),
                ('gender', models.BooleanField(choices=[(0, 'female'), (1, 'male')], default=1, verbose_name='gender')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Birth date')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('picture', models.ImageField(blank=True, null=True, upload_to=main.models.update_filename, verbose_name='Picture')),
            ],
        ),
    ]
