# Generated by Django 3.1.2 on 2020-10-31 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dolzhnost',
            options={},
        ),
        migrations.AddField(
            model_name='people',
            name='dolzhnost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.dolzhnost', verbose_name='Dolzhnost'),
        ),
    ]
