# Generated by Django 3.1.2 on 2021-01-04 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201123_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='about_us_ru',
            field=models.CharField(default='', max_length=500, verbose_name='About us'),
        ),
        migrations.AddField(
            model_name='about',
            name='about_us_tj',
            field=models.CharField(default='', max_length=500, verbose_name='About us'),
        ),
        migrations.AddField(
            model_name='about',
            name='history_ru',
            field=models.CharField(default='', max_length=1000, verbose_name='History'),
        ),
        migrations.AddField(
            model_name='about',
            name='history_tj',
            field=models.CharField(default='', max_length=1000, verbose_name='History'),
        ),
        migrations.AddField(
            model_name='about',
            name='princips_of_work_ru',
            field=models.CharField(default='', max_length=500, verbose_name='Princips_of_work'),
        ),
        migrations.AddField(
            model_name='about',
            name='princips_of_work_tj',
            field=models.CharField(default='', max_length=500, verbose_name='Princips_of_work'),
        ),
        migrations.AddField(
            model_name='about',
            name='znachenie_nazvaniya_ru',
            field=models.CharField(default='', max_length=500, verbose_name='Znachenie_nazvaniya'),
        ),
        migrations.AddField(
            model_name='about',
            name='znachenie_nazvaniya_tj',
            field=models.CharField(default='', max_length=500, verbose_name='Znachenie_nazvaniya'),
        ),
        migrations.AddField(
            model_name='development',
            name='name_ru',
            field=models.CharField(default='', max_length=50, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='development',
            name='name_tj',
            field=models.CharField(default='', max_length=50, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='development',
            name='text_ru',
            field=models.CharField(default='', max_length=200, verbose_name='text'),
        ),
        migrations.AddField(
            model_name='development',
            name='text_tj',
            field=models.CharField(default='', max_length=200, verbose_name='text'),
        ),
        migrations.AddField(
            model_name='dolzhnost',
            name='name_ru',
            field=models.CharField(default='', max_length=100, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='dolzhnost',
            name='name_tj',
            field=models.CharField(default='', max_length=100, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='frameworkcategories',
            name='name_ru',
            field=models.CharField(default='', max_length=100, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='frameworkcategories',
            name='name_tj',
            field=models.CharField(default='', max_length=100, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='frameworkcategories',
            name='text_ru',
            field=models.CharField(default='', max_length=1000, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='frameworkcategories',
            name='text_tj',
            field=models.CharField(default='', max_length=1000, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='main',
            name='main_words_ru',
            field=models.CharField(default='', max_length=150, verbose_name='main_words'),
        ),
        migrations.AddField(
            model_name='main',
            name='main_words_tj',
            field=models.CharField(default='', max_length=150, verbose_name='main_words'),
        ),
        migrations.AddField(
            model_name='main',
            name='sub_words_ru',
            field=models.CharField(default='', max_length=150, verbose_name='sub_words'),
        ),
        migrations.AddField(
            model_name='main',
            name='sub_words_tj',
            field=models.CharField(default='', max_length=150, verbose_name='sub_words'),
        ),
        migrations.AddField(
            model_name='people',
            name='first_name_ru',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='people',
            name='first_name_tj',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='people',
            name='last_name_ru',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='people',
            name='last_name_tj',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='people',
            name='middle_name_ru',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='middle name'),
        ),
        migrations.AddField(
            model_name='people',
            name='middle_name_tj',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='middle name'),
        ),
        migrations.AddField(
            model_name='technologies',
            name='name_ru',
            field=models.CharField(default='', max_length=100, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='technologies',
            name='name_tj',
            field=models.CharField(default='', max_length=100, verbose_name='Name'),
        ),
    ]
