# Generated by Django 3.1.2 on 2020-10-31 10:54

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201031_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_us', models.CharField(max_length=500, verbose_name='About us')),
                ('history', models.CharField(max_length=1000, verbose_name='History')),
                ('znachenie_nazvaniya', models.CharField(max_length=500, verbose_name='Znachenie_nazvaniya')),
                ('princips_of_work', models.CharField(max_length=500, verbose_name='Princips_of_work')),
            ],
        ),
        migrations.CreateModel(
            name='OurPhotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to=main.models.update_filenamephoto, verbose_name='Picture')),
            ],
        ),
    ]
