# Generated by Django 3.1.2 on 2021-01-04 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210104_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='about_us_ru',
            field=models.CharField(default='', max_length=500, verbose_name='About us ru'),
        ),
        migrations.AlterField(
            model_name='about',
            name='about_us_tj',
            field=models.CharField(default='', max_length=500, verbose_name='About us tj'),
        ),
    ]
