# Generated by Django 3.1.2 on 2020-10-31 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_about_ourphotos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dolzhnost',
            name='code',
            field=models.CharField(max_length=10, verbose_name='Code'),
        ),
    ]
