# Generated by Django 3.1.2 on 2020-11-09 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_frameworkcategories_technologies'),
    ]

    operations = [
        migrations.AddField(
            model_name='frameworkcategories',
            name='position',
            field=models.IntegerField(default=0, verbose_name='Position'),
        ),
    ]
