# Generated by Django 3.1.2 on 2020-11-10 04:36

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_frameworkcategories_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technologies',
            name='svg',
            field=tinymce.models.HTMLField(max_length=5000, verbose_name='Svg'),
        ),
    ]
