# Generated by Django 3.1.2 on 2020-11-15 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20201113_1813'),
    ]

    operations = [
        migrations.CreateModel(
            name='Development',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='main_words')),
                ('text', models.CharField(max_length=200, verbose_name='sub_words')),
                ('position', models.IntegerField(default=0, verbose_name='Position')),
            ],
        ),
    ]
